### ISSUE TITLE
Converting Lealla to Huggingface's sentence transformer

### ISSUE THREAD

**Issue by temiwale88** [setu4993/convert-labse-tf-pt#25]
Hello setu -

Thanks for your work on this repository. I've tried following your directions but I have been stuck on `poetry` let alone actually getting a model, [LEALLA](https://tfhub.dev/google/LEALLA/LEALLA-large/1), from Thub to Huggingface hub. Could you please use your script to convert this model to a sentence transformer in huggingface?
This lightweight LABSE is critical to a project I'm working on. Also, is there an alternative to using poetry? It's disappointingly cumbersome to get it working on Windows.

Thanks!

**Comment by setu4993** [comment]
Hey @temiwale88, thanks for opening this issue and providing this feedback.

I can take a look at this new model over the weekend to see what it'll take.

If you just want to install it, this package is published on [PyPI](https://pypi.org/project/convert-labse-tf-pt/), so you could just `pip install` it instead of building with `poetry` from the repo.

**Comment by temiwale88** [comment]
Hello @setu4993 . To confirm:
1. I can try to use this package for the new models? 
2. How do I run it in place of `poetry run` commands or are the commands the same after `pip install`?

Thank you! I get the following error when I try it with PyPi. 

![image](https://github.com/setu4993/convert-labse-tf-pt/assets/21104282/cd76646f-13f6-4570-a0ee-f19aa7c62e87)

**Comment by temiwale88** [comment]
Also @setu4993, if you're able to get your script to work for LEALLA-Large and make it part of the sentence-transformer family in hugging-face, could you kindly use the same script for -small and -base? [See here for their TfHub links](https://tfhub.dev/google/collections/LEALLA/1).

I can confidently say that I've invested hours, and lack of sleep, into trying to follow your wonderful work on my Windows machine both through `poetry` and **PyPi** as stated. All efforts have failed (and I think you can't install the `jaxlib` dependency on a Windows machine anyway). Sigh. Thank you!

**Comment by setu4993** [comment]
@temiwale88 :

Ah, I realized from your screenshot that I actually haven't published the latest versions of this package to PyPI. Once installed from there, you could just drop the `poetry run` piece from all of the commands and execute them directly in venv it was installed in `convert_labse ...`.

Regardless of this aspect, though, it wouldn't work directly and would require because there's a slight difference in layer names and model architecture for the LEALLA models.

I spent some time on this today, and think they're migrate-able. I'm close and should be able to spend some more time on it over the weekend and see how far I get.

I'll post back here in a couple days with an update one way or the other.

**Comment by temiwale88** [comment]
@setu4993 I am immensely grateful that you'll try to do this for the models. Thank you! Idea for you: could you write a generalizable package that converts TfHub models to Huggingface's hub? I think it could be a high impact package (or even YouTube tutorial on how we can do it ourselves). I recognized that this capability is lacking during my search for this current project I'm working on. It might be useful for others and me in the future. Anyways, this is my focus now. Thank you!

**Comment by setu4993** [comment]
Hey @temiwale88, quick update: I managed to export all of the LEALLA models into the HF format and they're being uploaded to the HF hub right now (slow upload speeds today, so will likely be a couple hours before all's done).

- [LEALLA-small](https://huggingface.co/setu4993/LEALLA-small)
- [LEALLA-base](https://huggingface.co/setu4993/LEALLA-base)
- [LEALLA-large](https://huggingface.co/setu4993/LEALLA-large)

Full disclosure: I haven't had a chance to write tests and validate the output embeddings produced to compare with the TF Hub versions yet. I might have some bandwidth to do that over the next few days and update the docs after that.

> Idea for you: could you write a generalizable package that converts TfHub models to Huggingface's hub?  I think it could be a high impact package (or even YouTube tutorial on how we can do it ourselves).

I'm not qualified to do that, honestly :). There's a few tricky parts about model conversions:
1. Model architecture: That is pretty nice about this class of models since they're all BERT-based and so it's a pretty standard architecture. I started pursuing this for the [Universal Sentence Encoder](https://tfhub.dev/google/collections/universal-sentence-encoder) models a couple years ago (see: https://github.com/setu4993/convert-use-tf-pt) but this was notoriously hard to get around.
2. Size and dimensions of layers: When we have the code for this, it's easy to migrate, but doing this straight from the model is tricky.
3. Name mapping: This is the trickiest and most fallible part with transferring these models since each layer has to be ~manually mapped. Everyone training their models names these ever so slightly differently that an automatic map is next to impossible.

---

Anyway, hope this helps. I'll leave this issue open until I've had a chance to add the tests and update the docs in this repo.

**Comment by temiwale88** [comment]
@setu4993 . **You have blessed me immensely!** I can pull each of these in with **`AutoTokenizer`** and **`AutoModel`**. I can't use sentence_transformer class. But that's fine for now. In my little test (semantic similarity between an English and Yoruba sentence), LEALLA-small and -base relatively work well, comparably with LABSE. However, -large is markedly off which is weird. But -small will do! Thank you! And let me know if there are any other updates. Also, you can include the TfHub and research article in your Huggingface hub for each model.

**Comment by temiwale88** [comment]
So when I try to get the similarity between the two sentences below I get different results between using TfHub and the one you uploaded to Huggingface:

![image](https://github.com/setu4993/convert-labse-tf-pt/assets/21104282/edd0c0e6-25fa-41c7-8036-1512ff193b36)
![image](https://github.com/setu4993/convert-labse-tf-pt/assets/21104282/bc6410cc-cf8e-481f-ab8a-8e5d0f5c3d62)
**versus**
![image](https://github.com/setu4993/convert-labse-tf-pt/assets/21104282/50a18cfc-e7ff-4921-8372-ce6b478cdf39)
![image](https://github.com/setu4993/convert-labse-tf-pt/assets/21104282/a90eb061-6591-4309-ac95-3f0b44243eef)
![image](https://github.com/setu4993/convert-labse-tf-pt/assets/21104282/b788f8f9-8232-424a-848f-b906e517fc9c)

 The so called "italian_sentence" is actually Urdu (I'm just lazy to change the name) and it has nothing to do with the English word "Tokenization". Thus the TfHub version is correct. I tried several sentences but the results are inconsistent. I wonder if it's the pooling layer?

**Comment by temiwale88** [comment]
P.s. Do you have a **Buy me a coffee** or Venmo? My wife agrees that we should say 'thank you!' tangibly. I can tell you more of my project if we ever get to connect.

**Comment by setu4993** [comment]
Glad the models load well for you, @temiwale88! I don't use `sentence-transformers` myself and it has been a couple years since I looked at its source to know if / how it'd work with it.

> TfHub version is correct. I tried several sentences but the results are inconsistent. I wonder if it's the pooling layer?

I did suspect that yesterday (thus the ^ warning) and found an issue with the `token_type_embeddings` which took a while to debug and looking through the TF graph (fix in fc0bfcf), which I have now fixed and am uploading the new versions of the models right now (slow uploads, again, but I can see that small is uploaded and the other 2 are in progress). Try getting the new models from the HF hub and they should have this fixed.

Also, to get equivalent embeddings to the TF Hub ones, we need to apply L2-norm to the pooler output. I haven't tested the below exactly, but it should work (might require minor tweaks).

```python
import torch
import torch.nn.functional as F
from transformers import BertModel, BertTokenizerFast


tokenizer = BertTokenizerFast.from_pretrained("setu4993/LEALLA-small")
model = BertModel.from_pretrained("setu4993/LEALLA-small")
model = model.eval()

english_sentences = [...]
italian_sentences = [...]

english_inputs = tokenizer(english_sentences, return_tensors="pt", padding=True)
italian_inputs = tokenizer(italian_sentences, return_tensors="pt", padding=True)

with torch.no_grad():
    english_outputs = model(**english_inputs)
    italian_outputs = model(**italian_inputs)


def similarity(embeddings_1, embeddings_2):
    normalized_embeddings_1 = F.normalize(embeddings_1, p=2)
    normalized_embeddings_2 = F.normalize(embeddings_2, p=2)
    return torch.matmul(
        normalized_embeddings_1, normalized_embeddings_2.transpose(0, 1)
    )

print(similarity(english_embeddings, italian_embeddings))
```

I have validated in a notebook that the embeddings produced with the updated models are within a tiny tolerance window of the TF hub ones, so the similarity should be very close to what's expected from TF hub.

> Also, you can include the TfHub and research article in your Huggingface hub for each model.

That is indeed the plan for once I get around to writing the docs (after the tests). I have a busy couple weeks upcoming so it's possible I don't get around to it during that time. But the above code snippet should suffice to get you over the hump in the meanwhile :).

I'll post back here once that's done.

> P.s. Do you have a **Buy me a coffee** or Venmo? My wife agrees that we should say 'thank you!' tangibly.

That's very generous of you 🙂. Please just take an evening to celebrate with your wife and family instead!

> I can tell you more of my project if we ever get to connect.

My email is on my profile page if you ever want to reach out.

**Comment by temiwale88** [comment]
@setu4993 . Muchas gracias my bro! Thanks for blessing us/me with these models. I pray others find it and download it from Huggingface hub.

**Comment by setu4993** [comment]
I've finally got a chance to add tests and update the model cards. I released them all on HF hub and here, and tagged the latest release [v3.0.0](https://github.com/setu4993/convert-labse-tf-pt/releases/tag/v3.0.0).

Going to close this since this is now complete.

Hope you find LEALLA useful for your project!

**Comment by temiwale88** [comment]
Thank you @setu4993 . I'm using the previous release and it's all good! Do I need this updated version? Thank you again!

**Comment by setu4993** [comment]
> Thank you @setu4993 . I'm using the previous release and it's all good! Do I need this updated version? Thank you again!

There's no model / tokenizer changes so the versions should be identical and shouldn't require updating :).
